// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skill_api.proto

package com.congcoi123.example.backend.skill;

/**
 * Protobuf type {@code com.congcoi123.example.backend.skill.CastSkillRequestResponse}
 */
public  final class CastSkillRequestResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.congcoi123.example.backend.skill.CastSkillRequestResponse)
    CastSkillRequestResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CastSkillRequestResponse.newBuilder() to construct.
  private CastSkillRequestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CastSkillRequestResponse() {
    effective_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CastSkillRequestResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.congcoi123.example.backend.skill.Skill.Builder subBuilder = null;
            if (skill_ != null) {
              subBuilder = skill_.toBuilder();
            }
            skill_ = input.readMessage(com.congcoi123.example.backend.skill.Skill.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(skill_);
              skill_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            effective_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.congcoi123.example.backend.skill.SkillApiProto.internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.congcoi123.example.backend.skill.SkillApiProto.internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.congcoi123.example.backend.skill.CastSkillRequestResponse.class, com.congcoi123.example.backend.skill.CastSkillRequestResponse.Builder.class);
  }

  public static final int SKILL_FIELD_NUMBER = 1;
  private com.congcoi123.example.backend.skill.Skill skill_;
  /**
   * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
   */
  public boolean hasSkill() {
    return skill_ != null;
  }
  /**
   * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
   */
  public com.congcoi123.example.backend.skill.Skill getSkill() {
    return skill_ == null ? com.congcoi123.example.backend.skill.Skill.getDefaultInstance() : skill_;
  }
  /**
   * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
   */
  public com.congcoi123.example.backend.skill.SkillOrBuilder getSkillOrBuilder() {
    return getSkill();
  }

  public static final int EFFECTIVE_FIELD_NUMBER = 2;
  private boolean effective_;
  /**
   * <code>bool effective = 2;</code>
   */
  public boolean getEffective() {
    return effective_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (skill_ != null) {
      output.writeMessage(1, getSkill());
    }
    if (effective_ != false) {
      output.writeBool(2, effective_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (skill_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSkill());
    }
    if (effective_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, effective_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.congcoi123.example.backend.skill.CastSkillRequestResponse)) {
      return super.equals(obj);
    }
    com.congcoi123.example.backend.skill.CastSkillRequestResponse other = (com.congcoi123.example.backend.skill.CastSkillRequestResponse) obj;

    boolean result = true;
    result = result && (hasSkill() == other.hasSkill());
    if (hasSkill()) {
      result = result && getSkill()
          .equals(other.getSkill());
    }
    result = result && (getEffective()
        == other.getEffective());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSkill()) {
      hash = (37 * hash) + SKILL_FIELD_NUMBER;
      hash = (53 * hash) + getSkill().hashCode();
    }
    hash = (37 * hash) + EFFECTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEffective());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.congcoi123.example.backend.skill.CastSkillRequestResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.congcoi123.example.backend.skill.CastSkillRequestResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.congcoi123.example.backend.skill.CastSkillRequestResponse)
      com.congcoi123.example.backend.skill.CastSkillRequestResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.congcoi123.example.backend.skill.SkillApiProto.internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.congcoi123.example.backend.skill.SkillApiProto.internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.congcoi123.example.backend.skill.CastSkillRequestResponse.class, com.congcoi123.example.backend.skill.CastSkillRequestResponse.Builder.class);
    }

    // Construct using com.congcoi123.example.backend.skill.CastSkillRequestResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (skillBuilder_ == null) {
        skill_ = null;
      } else {
        skill_ = null;
        skillBuilder_ = null;
      }
      effective_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.congcoi123.example.backend.skill.SkillApiProto.internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_descriptor;
    }

    @java.lang.Override
    public com.congcoi123.example.backend.skill.CastSkillRequestResponse getDefaultInstanceForType() {
      return com.congcoi123.example.backend.skill.CastSkillRequestResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.congcoi123.example.backend.skill.CastSkillRequestResponse build() {
      com.congcoi123.example.backend.skill.CastSkillRequestResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.congcoi123.example.backend.skill.CastSkillRequestResponse buildPartial() {
      com.congcoi123.example.backend.skill.CastSkillRequestResponse result = new com.congcoi123.example.backend.skill.CastSkillRequestResponse(this);
      if (skillBuilder_ == null) {
        result.skill_ = skill_;
      } else {
        result.skill_ = skillBuilder_.build();
      }
      result.effective_ = effective_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.congcoi123.example.backend.skill.CastSkillRequestResponse) {
        return mergeFrom((com.congcoi123.example.backend.skill.CastSkillRequestResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.congcoi123.example.backend.skill.CastSkillRequestResponse other) {
      if (other == com.congcoi123.example.backend.skill.CastSkillRequestResponse.getDefaultInstance()) return this;
      if (other.hasSkill()) {
        mergeSkill(other.getSkill());
      }
      if (other.getEffective() != false) {
        setEffective(other.getEffective());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.congcoi123.example.backend.skill.CastSkillRequestResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.congcoi123.example.backend.skill.CastSkillRequestResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.congcoi123.example.backend.skill.Skill skill_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.congcoi123.example.backend.skill.Skill, com.congcoi123.example.backend.skill.Skill.Builder, com.congcoi123.example.backend.skill.SkillOrBuilder> skillBuilder_;
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    public boolean hasSkill() {
      return skillBuilder_ != null || skill_ != null;
    }
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    public com.congcoi123.example.backend.skill.Skill getSkill() {
      if (skillBuilder_ == null) {
        return skill_ == null ? com.congcoi123.example.backend.skill.Skill.getDefaultInstance() : skill_;
      } else {
        return skillBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    public Builder setSkill(com.congcoi123.example.backend.skill.Skill value) {
      if (skillBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        skill_ = value;
        onChanged();
      } else {
        skillBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    public Builder setSkill(
        com.congcoi123.example.backend.skill.Skill.Builder builderForValue) {
      if (skillBuilder_ == null) {
        skill_ = builderForValue.build();
        onChanged();
      } else {
        skillBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    public Builder mergeSkill(com.congcoi123.example.backend.skill.Skill value) {
      if (skillBuilder_ == null) {
        if (skill_ != null) {
          skill_ =
            com.congcoi123.example.backend.skill.Skill.newBuilder(skill_).mergeFrom(value).buildPartial();
        } else {
          skill_ = value;
        }
        onChanged();
      } else {
        skillBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    public Builder clearSkill() {
      if (skillBuilder_ == null) {
        skill_ = null;
        onChanged();
      } else {
        skill_ = null;
        skillBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    public com.congcoi123.example.backend.skill.Skill.Builder getSkillBuilder() {
      
      onChanged();
      return getSkillFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    public com.congcoi123.example.backend.skill.SkillOrBuilder getSkillOrBuilder() {
      if (skillBuilder_ != null) {
        return skillBuilder_.getMessageOrBuilder();
      } else {
        return skill_ == null ?
            com.congcoi123.example.backend.skill.Skill.getDefaultInstance() : skill_;
      }
    }
    /**
     * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.congcoi123.example.backend.skill.Skill, com.congcoi123.example.backend.skill.Skill.Builder, com.congcoi123.example.backend.skill.SkillOrBuilder> 
        getSkillFieldBuilder() {
      if (skillBuilder_ == null) {
        skillBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.congcoi123.example.backend.skill.Skill, com.congcoi123.example.backend.skill.Skill.Builder, com.congcoi123.example.backend.skill.SkillOrBuilder>(
                getSkill(),
                getParentForChildren(),
                isClean());
        skill_ = null;
      }
      return skillBuilder_;
    }

    private boolean effective_ ;
    /**
     * <code>bool effective = 2;</code>
     */
    public boolean getEffective() {
      return effective_;
    }
    /**
     * <code>bool effective = 2;</code>
     */
    public Builder setEffective(boolean value) {
      
      effective_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool effective = 2;</code>
     */
    public Builder clearEffective() {
      
      effective_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.congcoi123.example.backend.skill.CastSkillRequestResponse)
  }

  // @@protoc_insertion_point(class_scope:com.congcoi123.example.backend.skill.CastSkillRequestResponse)
  private static final com.congcoi123.example.backend.skill.CastSkillRequestResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.congcoi123.example.backend.skill.CastSkillRequestResponse();
  }

  public static com.congcoi123.example.backend.skill.CastSkillRequestResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CastSkillRequestResponse>
      PARSER = new com.google.protobuf.AbstractParser<CastSkillRequestResponse>() {
    @java.lang.Override
    public CastSkillRequestResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CastSkillRequestResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CastSkillRequestResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CastSkillRequestResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.congcoi123.example.backend.skill.CastSkillRequestResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

