// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skill_api.proto

package com.congcoi123.example.backend.skill;

public interface CastSkillRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.congcoi123.example.backend.skill.CastSkillRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
   */
  boolean hasSkill();
  /**
   * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
   */
  com.congcoi123.example.backend.skill.Skill getSkill();
  /**
   * <code>.com.congcoi123.example.backend.skill.Skill skill = 1;</code>
   */
  com.congcoi123.example.backend.skill.SkillOrBuilder getSkillOrBuilder();
}
