// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skill.proto

package com.congcoi123.example.backend.skill;

public interface SkillOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.congcoi123.example.backend.skill.Skill)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 damage = 2;</code>
   */
  int getDamage();
}
