// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skill_api.proto

package com.congcoi123.example.backend.skill;

public final class SkillApiProto {
  private SkillApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_congcoi123_example_backend_skill_CastSkillRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_congcoi123_example_backend_skill_CastSkillRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017skill_api.proto\022$com.congcoi123.exampl" +
      "e.backend.skill\032\013skill.proto\"N\n\020CastSkil" +
      "lRequest\022:\n\005skill\030\001 \001(\0132+.com.congcoi123" +
      ".example.backend.skill.Skill\"i\n\030CastSkil" +
      "lRequestResponse\022:\n\005skill\030\001 \001(\0132+.com.co" +
      "ngcoi123.example.backend.skill.Skill\022\021\n\t" +
      "effective\030\002 \001(\0102\242\002\n\010SkillAPI\022\203\001\n\tCastSki" +
      "ll\0226.com.congcoi123.example.backend.skil" +
      "l.CastSkillRequest\032>.com.congcoi123.exam" +
      "ple.backend.skill.CastSkillRequestRespon" +
      "se\022\217\001\n\021CastMultipleSkill\0226.com.congcoi12" +
      "3.example.backend.skill.CastSkillRequest" +
      "\032>.com.congcoi123.example.backend.skill." +
      "CastSkillRequestResponse(\0010\001B7\n$com.cong" +
      "coi123.example.backend.skillB\rSkillApiPr" +
      "otoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.congcoi123.example.backend.skill.SkillProto.getDescriptor(),
        }, assigner);
    internal_static_com_congcoi123_example_backend_skill_CastSkillRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_congcoi123_example_backend_skill_CastSkillRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_congcoi123_example_backend_skill_CastSkillRequest_descriptor,
        new java.lang.String[] { "Skill", });
    internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_congcoi123_example_backend_skill_CastSkillRequestResponse_descriptor,
        new java.lang.String[] { "Skill", "Effective", });
    com.congcoi123.example.backend.skill.SkillProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
