// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skill.proto

package com.congcoi123.example.backend.skill;

public final class SkillProto {
  private SkillProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_congcoi123_example_backend_skill_Skill_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_congcoi123_example_backend_skill_Skill_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013skill.proto\022$com.congcoi123.example.ba" +
      "ckend.skill\"%\n\005Skill\022\014\n\004name\030\001 \001(\t\022\016\n\006da" +
      "mage\030\002 \001(\rB4\n$com.congcoi123.example.bac" +
      "kend.skillB\nSkillProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_congcoi123_example_backend_skill_Skill_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_congcoi123_example_backend_skill_Skill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_congcoi123_example_backend_skill_Skill_descriptor,
        new java.lang.String[] { "Name", "Damage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
