server:
  port: 8080

management:
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      base-path: /

grpc:
  port: 6565
  ssl:
    server-certificate: classpath:service-dummy.cert
    server-key: classpath:/service-dummy.key
  enabled: true
  enable-reflection: true

spring:
  main:
    web-application-type: reactive

  http:
    log-request-details: true

  h2:
    console:
      enabled: true
      path: /h2

  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
