server:
  port: 8080

grpc:
  port: 6565
  ssl:
    server-certificate: classpath:service-dummy.cert
    server-key: classpath:/service-dummy.key
  enabled: true
  enable-reflection: true

spring:
  main:
    web-application-type: reactive

  http:
    log-request-details: true

  h2:
    console:
      enabled: true
      path: h2-console
      settings:
        trace: true

  datasource:
    username: sa
    url: mem:testdb;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    password:
    dbfile: /Users/kong/testdb
